### ISSUE TITLE
How can I uninstall the framework

### ISSUE THREAD

**Issue by Ninvel** [xicodomingues/francinette#10]
I don't need more this program but I don't know how can I uninstall, how can I uninstall this app framework

**Comment by xicodomingues** [comment]
To uninstall `francinette` delete the `francinette` folder. It should be located under your `$HOME` directory (`/User/<your_username>/` or `/home/<your_username>/`)

You also need to remove the automatically created aliases. For that open your `~/.zshrc` file and delete the lines:

```
alias francinette="$HOME"/francinette/tester.sh
alias paco="$HOME"/francinette/tester.sh
```

I've also added this information to the README.

Thank you for using `francinette`! :D
