### ISSUE TITLE
norminette not working after installing francinette

### ISSUE THREAD

**Issue by hu8813** [xicodomingues/francinette#11]
![Screenshot_from_2022-10-10_19-44-49](https://user-images.githubusercontent.com/38990435/194933325-29034f0a-036e-4cda-887b-d70b593d6e51.png)

hi.
norminette is not working after installing francinette on school computer
(asks now for some write permissions which i can not sudo on school pc)
thanks

**Comment by xicodomingues** [comment]
Hey.

Francinette only really works on MacOS. Only a few tests work on Linux. You can try installing it on the school pc, but I don't think it will work well.

To do that you can download the script that is in 
https://github.com/xicodomingues/francinette/blob/ab49857e546ea62ec69378685b86ed4e16309c20/bin/install.sh

and delete these lines:
https://github.com/xicodomingues/francinette/blob/ab49857e546ea62ec69378685b86ed4e16309c20/bin/install.sh#L13-L21

and then run it. It will not try to install anything, but I'm not sure it will work.
