### ISSUE TITLE
apt not working on arch based system

### ISSUE THREAD

**Issue by PrimeO7** [xicodomingues/francinette#12]
[install.sh](https://github.com/xicodomingues/francinette/blob/ec4fe802f0fa67da89a09dac64a42d6b23abf3ae/bin/install.sh#L13)

`apt` is being used but only works on debian based systems and its derivatives.
I use arch (btw) and it is using [pacman](https://wiki.archlinux.org/title/pacman) as its package manager

**Comment by PrimeO7** [comment]
resolves #13

**Comment by xicodomingues** [comment]
Thank you for the pull request!
