### ISSUE TITLE
incorrect test for calloc in alelievr/libft-unit-test

### ISSUE THREAD

**Issue by Oktosha** [xicodomingues/francinette#15]
The first calloc test in libft-unit-test tester timeouts on my laptop but not in school.

I looked at the test, and I think that the problem is in the test rather than in my code. In all other calloc tester functions the pointer to the tested function is casted to `typeof(calloc)*` like [this](https://github.com/xicodomingues/libft-unit-test/blob/f3af320e6b6e94b87b0cdee74761d2bd19bd202b/src/test_functions.c#L1752) but in `test_ft_calloc_free` it is casted to `void *(*)(size_t)` like [this](https://github.com/xicodomingues/libft-unit-test/blob/f3af320e6b6e94b87b0cdee74761d2bd19bd202b/src/test_functions.c#L1743). Later it [is called](https://github.com/xicodomingues/libft-unit-test/blob/f3af320e6b6e94b87b0cdee74761d2bd19bd202b/src/test_functions.c#L1747) with one param. But that's UB because `ft_calloc` has 2 params.

I suggest replacing
```c
void *	(*ft_calloc)(size_t) = ptr;
...
free(ft_calloc(42));
```
with
```c
typeof(calloc)	*ft_calloc = ptr;
...
free(ft_calloc(42, 1));
```
or whatever value of the second parameter makes sense.

**Comment by xicodomingues** [comment]
Thank you for the report and the fix!

**Comment by Rodeo314** [comment]
Thanks, I was having the same issue but couldn't find the time to figure out the cause and/or fix :-)
