### ISSUE TITLE
All tests passes, although the Makefile doesn't work properly

### ISSUE THREAD

**Issue by MannBell** [xicodomingues/francinette#16]
# The `Moulinette` throws back my project twice, both times it is `Makefile` related problem:
## The 1st problem:
I was using `-I.` flag in the implicit rule of compilation(`%.o: %.c`), and i did put by mistake `<libft.h>` instead of `"libft.h"` in one of the files, but the `Makefile` just worked seamlessly without throwing any errors.(the three flags were used: `-Wall -Wextra -Werror`). The `Moulinette` doesn't seem to use the `-I.` flag in the first compilation test, and that threw an error, so I had to remove the `-I.` flag to fix the problem.
## The 2nd problem(which i find a more serious issue):
The tests don't test the `libft.a` library for compilation, my `Makefile` was creating the library `libft.a` with only one object file(`ft_isalpha.o`), and that was due to my misunderstanding(i was using `$<` instead of `$^`), when the `Moulinette` tried to test with my `libft.a` it threw and error because the next function to test(`ft_isdigit`) was not included in the library.
> I hope that i explained the problem well, and i hope that the problems that cost me 6 evaluation points (and lot of time) get fixed, so further students won't fall for the same problem.

**Comment by xicodomingues** [comment]
The only makefile tests that I have (that are not even mine) is that it compiles and creates the expected file: `libft.a` making them check the kind of nuances that failed the first problem is outside of my objective for the tests.

About the second problem, if the lib file `libft.a` was only created with one object file inside, then the tests fail to compile on my end, so I'm not really sure how to reproduce it.
