### ISSUE TITLE
LIBFT - Memmove && strrchr crash since v0.9.4

### ISSUE THREAD

**Issue by Laendrun** [xicodomingues/francinette#17]
I tested my Libft all day yesterday, everything was working fine, I had no issues.
Since this morning I get a crash on some tests for the Memmove && strrchr functions.
All these crashes appear in the *Alelievr* tester, and I think it has something to do with the tester since it's the "only" part that has been changed since yesterday.
```sh
[crash]: your memmove crash because it read too many bytes or attempt to read on dst !
 Test code:
 	int size = 10;
 	char *dst = electric_alloc(size);
 	char *data = electric_alloc(size);

 	__builtin___memset_chk (data, 'A', size, __builtin_object_size (data, 0));
 	ft_memmove(dst, data, size);
 	dst = electric_alloc_rev(size);
 	data = electric_alloc_rev(size);
 	__builtin___memset_chk (data, 'A', size, __builtin_object_size (data, 0));
 	ft_memmove(dst, data, size);
 	exit(TEST_SUCCESS);


 [crash]: your strrchr crash because it read too many bytes or attempt to write on s !
 Test code:
 	char *src = electric_alloc(10);

 	__builtin___strcpy_chk (src, "123456789", __builtin_object_size (src, 2 > 1 ? 1 : 0));
 	ft_strrchr(src, 'a');
 	src = electric_alloc_rev(10);
 	__builtin___strcpy_chk (src, "123456789", __builtin_object_size (src, 2 > 1 ? 1 : 0));
 	ft_strrchr(src, 'a');
 	exit(TEST_SUCCESS);
```

Let me know if you need more informations.
Btw I didn't test it at school, for now only on my personal macbook.

**Comment by JopjeKnopje** [comment]
Same issue here.

**Comment by xicodomingues** [comment]
On my end, for my version of `libft.a` those tests pass. So I'm assuming that the problem is on your code.
The error is that you are going out of bounds while reading the `dst` string.

Make sure that in your `while` you are not reading after you see the `'\0'` char signifying the end of the string.
