### ISSUE TITLE
At home

### ISSUE THREAD

**Issue by lebojo** [xicodomingues/francinette#19]
Hello, thanks for your amazing work! But we can't use it at home because we don't have the "norminette", cane we have an option to configure that? 
Thanks!

**Comment by Zopokx** [comment]
https://github.com/42School/norminette :)

**Comment by lebojo** [comment]
Thanks <3

**Comment by xicodomingues** [comment]
There is also the option `--ignore-norm` or `-in` that does not run `norminette`.
