### ISSUE TITLE
printf: cannot compile fsoares tests without passing c to ar

### ISSUE THREAD

**Issue by Rodeo314** [xicodomingues/francinette#21]
For some odd reason, ar is printing `ar: creating archive libftprintf.a` to stderr instead of stdout, causing the test to "fail" to compile.

This is easily worked around, but it would be nice is the tests could compile without having to forcibly silence ar. I am unsure how to proceed re: attempting to fix this on my own, however.

Regards,

Tim

**Comment by xicodomingues** [comment]
Weird, that does not really happen in my version of `ar`. I'm sure it is related to a new version of it. I'm not sure where is the problem or how to fix it for now.

I'll look into it.

**Comment by Rodeo314** [comment]
> I'm sure it is related to a new version of it.

Not so new, as it occurs on the cluster iMacs (at least in Lausanne, Catalina 11.5.7, system-provided ar). Same under macOS Monterey here, too.

What happens is, as a result of ar writing to stderr, something happens somewhere causing the Halo spinner happens to not be enabled and francinette stops there:

https://github.com/xicodomingues/francinette/blob/master/testers/printf/Fsoares.py#L63

I've rarely ever used Python and am 100% unfamiliar with Halo, so I don't know what happens causing the spinner to end up disabled, sadly.

**Comment by xicodomingues** [comment]
I've looked into it, and to modify it to ignore stderr messages It's more work than it is worth. (I would need to change the function to then care about the return code, but I have lots of code that depends on the output, and only that).

I have some plans to refactor some parts of this app, especially everything that has to do with executing C code to be more centralized and in its own class.

I'll keep it in mind when I do that, so at that point I'll fix this case.

**Comment by Rodeo314** [comment]
Makes sense :-)
