### ISSUE TITLE
The new change on the error test is not graded by Moulinette

### ISSUE THREAD

**Issue by MannBell** [xicodomingues/francinette#27]
The new update that changed the error test took place after i got evaluated by Moulinette, Moulinette passed my work with full score, but when i tested my code again using the updated tester it showed me `KO` on the new tests (which are not used by Moulinette), that's why i guess that this test should be moved to the --strict flag, thank you.

**Comment by xicodomingues** [comment]
Passing francinette is not a garantee that will pass moulinette, and passing moulinette is not a garantee that will pass francinette.
I put the tests that make sense to me, and put some more esoteric tests behind the strict flag, but It's not really about passing the moulinette, even tho I say that in the test. I'll modify the text to reflect this.
