### ISSUE TITLE
Norminette checks everything

### ISSUE THREAD

**Issue by maplepy** [xicodomingues/francinette#28]
The norminette checks every file when it is supposed to check only files in the current directory, files needed in the project or files passed in the arguments.

With `paco strlcat` for instance, it will check any file instead of just testing strlcat

**Comment by maplepy** [comment]
Wouldn't it be better to only check for mandatory files? It currently tests any files in sub-folders even if they're not needed

**Comment by xicodomingues** [comment]
Francinette runs norminette on everything that will possibly be on the remote repo.

If you want `francinette` to ignore some files when doing the norm check (like your own mains, other tests, etc) add those files/directories to the `.gitignore` file. If they are ignored in git, they will not be checked by francinette

**Comment by maplepy** [comment]
> even tho it is friendly

wouldnt really say it is friendly when it runs the norminette on your test main (obviously not norm friendly) when you run your own tests 

I guess I just dont get the downgrade from libft-tester that was nice and clean only checking required files and outputting what file(s) had norm errors and what those were

**Comment by maplepy** [comment]
> add those files/directories to the `.gitignore`

that makes it a tedious process when you want to have those testers in your repo and still want to use your function. that's really not ideal
