### ISSUE TITLE
[Errno 2] No such file or directory: 'norminette'

### ISSUE THREAD

**Issue by isabel42** [xicodomingues/francinette#32]
Hello, 

I installed francinette and norminette in order to make Francinette work properly. 
I need help to undertand how Francinette is calling norminette. 
For some reason, norminette gets installed in the the library on my MAC. In order to make norminette work with command norminette I had to create an allias on . zshrc: alias norminette=/Users/IsabelTovar/Library/Python/3.9/bin/norminette

I feel some turn around must be applied also with Francinette so it calls the norminette at the right location. 

Thank you for your help! 

Isabel

**Comment by isabel42** [comment]
I found solution finally! 
instead of alias I inserted 
export PATH="/Users/isabeltovar/Library/Python/3.9/bin:$PATH"

Thank you!

**Comment by sargarse** [comment]
Hi Isabel,

I have the same problem, what is the file which you inserted this?
I tryed to write in .zshrc, with the other aliases, but it does not work.

I use MacOS 10.13.6

Thank you a lot!
S.

**Comment by igordotdev** [comment]
Hi @sargarse,
it is probably long after you've resolved your issue but I thought I would explain anyway:
**export** is a command that will affect envioremnt variables. Here Isabel simply added path to python binary files to **PATH** environment variable.
I hope my response clarified the solution of Isabel.

All the best,
Igor

**Comment by bacitoto** [comment]
Ubuntu WSL 2  (windows11)  here

adding to this
I had to add the following line to my .bashrc or .zshrc if you use zhs
export PATH="/home/your_username/.local/bin/:$PATH"
