### ISSUE TITLE
Printf tester with -b -s

### ISSUE THREAD

**Issue by VictorEgret** [xicodomingues/francinette#39]
When running "francinette -b -s" from ft_printf directory i get "The command was not found or was not executable: ./printf.out.".
I fixed it by changing line 79 of file "Fsoares.py" from this
```py
		errors = self.check_errors(self.run_tests("./printf.out"))
```
to this
```py
		errors = self.check_errors(self.run_tests("./printf_b.out" if self.exec_bonus else "./printf.out"))
```

**Comment by xicodomingues** [comment]
I've fixed it, but in another way.

Thank you for the issue!
