### ISSUE TITLE
shows failed test and passed test at the same place

### ISSUE THREAD

**Issue by mdabir1203** [xicodomingues/francinette#52]
**Describe the bug**

 - OS: MacOS 
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/66947064/217075228-859f90c7-bbec-43b3-9243-4b7357b69a82.png">

Ran the francinette --strict command and found this. If you observe it carefully the output of failed test and passed test both are showing the same functions.

**Comment by xicodomingues** [comment]
Interesting, it may be a bug that has been there for a while. I'll check it out

**Comment by xicodomingues** [comment]
It was indeed an old error. It should be fixed in the next release.
