### ISSUE TITLE
Francinette Strict doesn't work for printf

### ISSUE THREAD

**Issue by Turkmen48** [xicodomingues/francinette#80]
**Describe the bug**
Hello, last two days I'm trying to use francinette but it doesnt work. Actually it works wery well at first tests. But when I do francinette --strict it doesnt check my codes and not throws any error message. Btw I'm using ubuntu subsystem for windows and Wsl 2 on vscode.
 - OS: Ubuntu 20.04, WSL, Windows 10 pro x64

**Additional information**
I attached execution log and image. Also I try to test printf project. Libft worked wey well.
<img src="https://i.ibb.co/k6fYF6P/Screenshot-2.png" />
[execution.log](https://github.com/xicodomingues/francinette/files/13260395/execution.log)

**Comment by RPDJF** [comment]
https://github.com/xicodomingues/francinette#francinette

"``Francinette`` is only tested and confirmed to work on MacOS on non ARM chips. Some testers may work on Linux and ARM, but I give no guaranties of any test working or even compiling."

**Comment by Turkmen48** [comment]
😢
